### ISSUE TITLE
Bag does not remove

### ISSUE THREAD

**Issue by FBFezz** [andristum/dpclothing#3]
The bag option when i try click it again or /r or place it a few times does not remove it and if i try place it keeps placing bags (i do have latest version of dpemotes)

**Comment by FBFezz** [comment]
If i type /bag and then /r it fixes it but still have the issue with it using the Y menu

**Comment by andristum** [comment]
Not quite sure what you are talking about, theres currently no feature to remove bags, its just to open the bag, and there is no /r command in this resource.

**Comment by FBFezz** [comment]
Ahh i think it is conflicting with dp emotes, my apologies i phrased that terribly
